Train:
  batch_size: 64
  learning_rate: 0.8
  reg: 0.0005
  epochs: 10
  momentum: 0.91
  debug: True

Model:
  type: TwoLayerNet # SoftmaxRegression or TwoLayerNet
  hidden_size: 128 # only applicable for TwolayerNet
